Algoritmo "Avaliação ex 3"

VAR

filhos:inteiro
I:inteiro
salario:real
media:real
soma:real
dividir:real

INICIO

para I de 1 ate 10 faca
escreval("Informe o n° de filhos")
leia(filhos)
escreval("Informe o seu salário")
leia(salario)
soma <-salario+salario
dividir <- filhos+filhos/2

fimpara

escreval("A média do salário da população é",soma)
escreval("A média do n° de filhos é",dividir)
escreval("O maior salário",salario)

fimalgoritmo